# Generated by Django 4.0.5 on 2022-08-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='enter_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 11, 43, 27, 800707)),
        ),
    ]
