# Generated by Django 4.0.5 on 2022-08-10 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books_enter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='enter_date',
            field=models.DateField(default=datetime.date(2022, 8, 10), verbose_name='Дата загрузки книги'),
        ),
    ]
