# Generated by Django 4.0.5 on 2022-08-10 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_books_enter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='enter_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата загрузки книги'),
        ),
    ]
